apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  workspaces:
    - name: codebase
    - name: maven-settings
    - name: sonar-settings
  tasks:
    - name: repo-clone
      workspaces:
        - name: source
          workspace: codebase
      params:
        - name: repo-url
          value:  https://github.com/jglick/simple-maven-project-with-tests
      taskRef:
        name: clonetask
    - name: maven-run
      taskRef:
        name: maven
      runAfter:
        - repo-clone
      params:
        # - name: CONTEXT_DIR
        #   value: "apps/greeter/java/quarkus"
        - name: GOALS
          value:
            - -DskipTests
            - clean
            - package
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: codebase

    - name: code-analysis
      taskRef:
        name: sonarqube-scanner
      runAfter:
        - repo-clone
      params:
        - name: SONAR_HOST_URL
          value: http://20.219.167.173:9000/
      workspaces:
        - name: source
          workspace: codebase
        - name: sonar-settings
          workspace: sonar-settings
          

