apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces:
    - name: source
  steps:
    - name: volume-cleanup
      image: alpine
      workingDir: $(workspaces.source.path)
      script: |
        rm -rf ./source
        