apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: inittask
spec:
  workspaces:
    - name: source
  steps:
    - name: init-task
      image: hashicorp/terraform
      workingDir: $(workspaces.source.path)/source
      command:
        - terraform
        - init
 