apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: terraformpipelinerun
spec:
  workspaces:
    - name: codebase
      persistentVolumeClaim:
        claimName: tekton-pvc
  pipelineRef:
    name: terraformpipeline
  