apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: plantaskrun-
spec:
  serviceAccountName: azure-auth-sa
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: tekton-pvc
  taskRef:
    name: plantask